My_Block_Project/App_Blog/urls.py
from django.urls import path
from . import views
app_name='Blog'

urlpatterns=[
    path('',views.Blog_list_page.as_view(),name='blog_list'),
    path('create/',views.CreatBlock.as_view(),name='create_block'),
    path('detail/<str:slug>/',views.Detailblockfunc,name='detail_blog'),
    path('liked/<int:pk>/',views.likefunction,name='liked'),
    path('dislike/<int:pk>/',views.dislikefunc,name='dislike'),
    path('my-blog/',views.MyBlog_list.as_view(),name='my_blog'),
    path('edit-blog/<pk>/',views.UpdateBlog.as_view(),name='edit_blog'),
    path('delete-comment/<pk>/',views.DeleteMycomment,name='delete_comment'),
]

My_Block_Project/Login_app/urls.py
from django.urls import path
from . import views

app_name='Login_app'
urlpatterns=[
    path('singup/',views.sign_up,name='signup'),
    path('login/',views.mylogin,name='login'),
    path('logout/',views.logout_func,name='logout'),
    path('profile/',views.profile,name='profile'),
    path('change_profile/',views.userchange,name='changeProfile'),
    path('password/',views.change_passwordform,name='change_pass'),
    path('add_pro_pic/',views.update_pro_pic,name='add_pic'),
    path('change_pro_pic/',views.change_pro_pic,name='change_pic')
]

My_Block_Project/My_Block_Project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns,static
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),

    path('account/',include('Login_app.urls')),

    path('blog/',include('App_Blog.urls')),
    path('',views.index,name='index')

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

My_Block_Project/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>{% block title %} block project {% endblock %}</title>
    <style>
      {% block style %}
      {% endblock %}
    </style>
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'index' %}">Home</a>
      </li>
      {% if user.is_authenticated %}

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ request.user }}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="nav-link" href="{% url 'Blog:create_block' %}">create</a>
                  <a class="nav-link" href="{% url 'Blog:my_blog' %}">My Blog</a>
                  <a class="nav-link" href="{% url 'Login_app:profile' %}">Profile</a>
            <hr>
                  <a class="nav-link" href="{% url 'Login_app:logout' %}">Logout</a>

         </div>
      </li>

      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'Login_app:signup' %}">sign up </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'Login_app:login' %}">Login</a>
      </li>
      {% endif %}

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<!--<i class="fa fa-thumbs-up" aria-hidden="true"></i>-->

{% block body %}
{% endblock %}


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>