My_Block_Project/App_Blog/urls.py
from django.urls import path
from . import views
app_name='Blog'

urlpatterns=[
    path('',views.Blog_list_page.as_view(),name='blog_list'),
    path('create/',views.CreatBlock.as_view(),name='create_block'),
    path('detail/<str:slug>/',views.Detailblockfunc,name='detail_blog'),
    path('liked/<int:pk>/',views.likefunction,name='liked'),
    path('dislike/<int:pk>/',views.dislikefunc,name='dislike'),
    path('my-blog/',views.MyBlog_list.as_view(),name='my_blog'),
    path('edit-blog/<pk>/',views.UpdateBlog.as_view(),name='edit_blog'),
    path('delete-comment/<pk>/',views.DeleteMycomment,name='delete_comment'),
]

My_Block_Project/My_Block_Project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns,static
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),

    path('account/',include('Login_app.urls')),

    path('blog/',include('App_Blog.urls')),
    path('',views.index,name='index')

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

My_Block_Project/App_Blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Blog(models.Model):

    author=models.ForeignKey(User,related_name='post_author',on_delete=models.CASCADE)
    blog_title=models.CharField(max_length=264,verbose_name='put a title ')
    slug= models.SlugField(max_length=264,unique=True)
    blog_contant=models.TextField(verbose_name='What is your own mind ')
    blog_images=models.ImageField(upload_to='blog_images',verbose_name='Image')
    pub_date=models.DateTimeField(auto_now_add=True)
    update_date=models.DateTimeField(auto_now=True)

    class Meta:
        ordering=['-pub_date']

    def __str__(self):
        return self.blog_title

class Comment(models.Model):
    blog=models.ForeignKey(Blog,on_delete=models.CASCADE,related_name='blog_comment')
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='user_comment')
    comment=models.TextField()
    pub_date=models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering=['-pub_date']

    def __str__(self):
        return self.comment


class Liked(models.Model):
    blog=models.ForeignKey(Blog,on_delete=models.CASCADE,related_name='likes_blog')
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='like_user')

My_Block_Project/App_Blog/forms.py
from django import forms
from .models import Blog,Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)

My_Block_Project/App_Blog/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse,reverse_lazy
from django.views.generic import ListView,DetailView,CreateView,DeleteView,View,UpdateView
from .models import Comment,Liked,Blog
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import uuid
from .forms import CommentForm
from .models import Comment,Blog

# Create your views here.



class Blog_list_page(ListView):
    template_name = 'App_Blog/blog_list.html'
    model = Blog
    context_object_name = 'blogs'
    queryset = Blog.objects.order_by('-pub_date')

class MyBlog_list(LoginRequiredMixin,ListView):

    model = Blog
    template_name = 'App_Blog/my_block.html'

class UpdateBlog(LoginRequiredMixin,UpdateView):
    model = Blog
    fields = ('blog_title','blog_contant','blog_images')
    template_name = 'App_Blog/edit_block.html'

    def get_success_url(self,**kwargs):
        return reverse_lazy('Blog:detail_blog',kwargs={'slug':self.object.slug})




class CreatBlock(LoginRequiredMixin,CreateView):

    model = Blog
    fields = ('blog_title','blog_contant','blog_images')
    template_name = 'App_Blog/create_block.html'

    def form_valid(self, form):
        blog_obj=form.save(commit=False)
        blog_obj.author=self.request.user
        title=blog_obj.blog_title
        blog_obj.slug=title.replace(' ','-')+'-'+str(uuid.uuid4())
        blog_obj.save()
        return HttpResponseRedirect(reverse('index'))

@login_required(login_url='/')
def Detailblockfunc(request,slug):
    blog=Blog.objects.get(slug=slug)
    com=Comment.objects.filter(blog=blog)
    all_liked=Liked.objects.filter(blog=blog)
    form=CommentForm()
    if request.method == 'POST':
        form=CommentForm(request.POST)
        if form.is_valid():
            obj=form.save(commit=False)
            obj.blog=blog
            obj.user=request.user
            obj.save()
            return HttpResponseRedirect(reverse('Blog:detail_blog',kwargs={'slug':slug}))
    return render(request,'App_Blog/blog_detail.html',context={'blog':blog,'form':form,'com':com,'all_liked':len(all_liked)})

def likefunction(request,pk):
    blog=Blog.objects.get(pk=pk)
    user=request.user
    all_like= Liked.objects.all()
    already_like=Liked.objects.filter(blog=blog,user=user)
    if len(already_like)==0:
        like=Liked(blog=blog,user=user)
        like.save()
    if len(already_like)==1:
        already_like.delete()
    return HttpResponseRedirect(reverse('Blog:detail_blog',kwargs={'slug':blog.slug}))


def dislikefunc(request,pk):
    pass

# class DeleteMycomment(DeleteView):
#     model = Comment
#     context_object_name = 'delet_comment'
#     template_name = 'App_Blog/delete_comment.html'
#     success_url = reverse_lazy('index')

def DeleteMycomment(request,pk):
    delete_c=Comment.objects.get(pk=pk)
    if request.method== 'POST':
        delete_c.delete()
        return HttpResponseRedirect(reverse('Blog:detail_blog',kwargs={'slug':delete_c.blog.slug}))
    return render(request,'App_Blog/delete_comment.html',context={'ff':delete_c})

My_Block_Project/templates/App_Blog/blog_detail.html
{% extends 'base.html' %}
{% block title %}{{blog.blog_title}}{% endblock %}
{% block style %}

      {% endblock %}
{% block body %}
{% load crispy_forms_tags %}
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h1>{{ blog.blog_title}}</h1>
                <i>{{ blog.author}}</i><br>
                <small>Publish Date : {{ blog.pub_date}}</small><br>
                <small>Update Date : {{ blog.update_date}}</small>
                <p  class="mt-5 pt-3">Detail : </p>
                <p>{{ blog.blog_contant|linebreaks }}</p>
            </div>
            <div class="col-md-6">
                <img src="/media/{{ blog.blog_images }}" alt="{{blog.blog_title}}" width="100%">
            </div>
        </div>





   <div class="row">
            <div class="col-md-6">
                <p>{{all_liked}} Liked</p>
                <a href="{% url 'Blog:liked' blog.pk %}">  <svg width="25" height="25" style="color:black" viewBox="0 0 25 25" aria-label="clap"><g fill-rule="evenodd"><path d="M11.74 0l.76 2.97.76-2.97zM14.81 3.78l1.84-2.56-1.42-.47zM8.38 1.22l1.84 2.56L9.8.75zM20.38 21.62a5.11 5.11 0 0 1-3.16 1.61l.49-.45c2.88-2.89 3.45-5.98 1.69-9.21l-1.1-1.94-.96-2.02c-.31-.67-.23-1.18.25-1.55a.84.84 0 0 1 .66-.16c.34.05.66.28.88.6l2.85 5.02c1.18 1.97 1.38 5.12-1.6 8.1M7.1 21.1l-5.02-5.02a1 1 0 0 1 .7-1.7 1 1 0 0 1 .72.3l2.6 2.6a.44.44 0 0 0 .63-.62L4.1 14.04l-1.75-1.75a1 1 0 1 1 1.41-1.41l4.15 4.15a.44.44 0 0 0 .63 0 .44.44 0 0 0 0-.62L4.4 10.26 3.22 9.08a1 1 0 0 1 0-1.4 1.02 1.02 0 0 1 1.41 0l1.18 1.16L9.96 13a.44.44 0 0 0 .62 0 .44.44 0 0 0 0-.63L6.43 8.22a.99.99 0 0 1-.3-.7.99.99 0 0 1 .3-.7 1 1 0 0 1 1.41 0l7 6.98a.44.44 0 0 0 .7-.5l-1.35-2.85c-.31-.68-.23-1.19.25-1.56a.85.85 0 0 1 .66-.16c.34.06.66.28.88.6L18.63 14c1.57 2.88 1.07 5.54-1.55 8.16a5.62 5.62 0 0 1-5.06 1.65 9.35 9.35 0 0 1-4.93-2.72zM11 5.98l2.56 2.56c-.5.6-.56 1.41-.15 2.28l.26.56-4.25-4.25a.98.98 0 0 1-.12-.45 1 1 0 0 1 .29-.7 1.02 1.02 0 0 1 1.41 0zm8.89 2.06c-.38-.56-.9-.92-1.49-1.01a1.74 1.74 0 0 0-1.34.33c-.38.29-.61.65-.71 1.06a2.1 2.1 0 0 0-1.1-.56 1.78 1.78 0 0 0-.99.13l-2.64-2.64a1.88 1.88 0 0 0-2.65 0 1.86 1.86 0 0 0-.48.85 1.89 1.89 0 0 0-2.67-.01 1.87 1.87 0 0 0-.5.9c-.76-.75-2-.75-2.7-.04a1.88 1.88 0 0 0 0 2.66c-.3.12-.61.29-.87.55a1.88 1.88 0 0 0 0 2.66l.62.62a1.88 1.88 0 0 0-.9 3.16l5.01 5.02c1.6 1.6 3.52 2.64 5.4 2.96a7.16 7.16 0 0 0 1.18.1c1.03 0 2-.25 2.9-.7A5.9 5.9 0 0 0 21 22.24c3.34-3.34 3.08-6.93 1.74-9.17l-2.87-5.04z"></path></g></svg>
                </a>
                <a href="{% url 'Blog:dislike' blog.pk %}"><i class="fa fa-thumbs-down fa-2x" aria-hidden="true"></i></a>
                <p>Comment:</p>

                {% comment 'comment option is hare it is user comment ----------------------------------------------------------' %}
                {% for comment in blog.blog_comment.all %}
                <a href="">{{ comment.user }} </a><small> {{ comment }}</small>
                <p>{{comment.pub_date}}</p>
                {% endfor %}
                {% endcomment %}


                     {% for x in com %}
                <hr>
                        <div class="row">

                            <div class="col-md-8">

                                    <a href="">{{ x.user }} </a><small> {{ x }}</small>
                                    <p>{{x.pub_date}}</p>
                            </div>
                                <div class="col-md-4">
                                        {% if x.user == request.user%}
                                            <div class="nav-item dropdown">
                                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">action</a>
                                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                                          <a class="nav-link" href="{% url 'Blog:delete_comment' x.pk %}">delete</a>
                                                          <a class="nav-link" href="">edit</a>
                                                    </div>
                                        </div>
                                        {% endif %}

                                </div>
                        </div>

                     {% endfor %}



        </div>


                    <div class="col-md-6">
                        <form action="" method="post">
                            {% csrf_token %}
                            {{form|crispy }}
                            <input type="submit" value="comment">
                        </form>
                    </div>
                </div>

    </div>
{% endblock %}

My_Block_Project/templates/App_Blog/blog_list.html
{% extends 'base.html' %}

{% block title %} home {% endblock %}

{% block body %}
    <div class="container">

             {% for blog in blogs %}
            <div class="row my-3">

                <div class="col-md-3 mb-4">

                    <img src="/media/{{blog.blog_images}}" alt="" width="100%">
                </div>
                <div class="col-md-9 mb-4">
                     <h1>{{ blog.blog_title}}</h1>
                    <small>{{ blog.pub_date }}</small>
                    <p class="mb-1">{{ blog.blog_contant|truncatewords:10}}</p>
                    
                    <span>read more <a href="{% url 'Blog:detail_blog' blog.slug %}">hare</a></span>
                    <p>produce by @{{blog.author}}</p>
                </div>
             </div>
            <hr>
            {% endfor %}


    </div>
{% endblock %}

My_Block_Project/templates/App_Blog/create_block.html
{% extends 'base.html' %}
{% block title %}{% endblock %}
{% block body %}
{% load crispy_forms_tags %}
<div class="container">
    <form action="" method="POST"  enctype="multipart/form-data">
    {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-info btn-sm">
    </form>
</div>
{% endblock %}

My_Block_Project/templates/App_Blog/delete_comment.html
{% extends 'base.html' %}
{% block title %}{% endblock %}
{% block body %}
<h3>your comment is <i>{{ff}}</i>, Are you sure want to delete this comment ?</h3>
<form action="" method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger btn-sm" value="delete">
    <button class="btn btn-info btn-sm"><a href="{% url 'Blog:detail_blog' ff.blog.slug %}">cancle</a></button>
</form>
{% endblock %}

My_Block_Project/templates/App_Blog/edit_block.html
{% extends 'base.html' %}
{% block title %}{% endblock %}
{% block body %}
{% load crispy_forms_tags %}
<div class="container">
    {% if blog.author == request.user %}
    <form action="" method="post" enctype="multipart/form-data">
         {% csrf_token %}
        {{ form|crispy }}
        <input type="submit">
    </form>
    {% endif %}
</div>
{% endblock %}

My_Block_Project/templates/App_Blog/my_block.html
{% extends 'base.html' %}
{% block title %}{% endblock %}
{% block body %}
<div class="container">
    {% for x in user.post_author.all %}
        <h1>{{ x.blog_title }}</h1>
        <small>{{ x.pub_date }}</small>
        <div class="row">
            <div class="col-md-4">
                <img src="/media/{{x.blog_images}}" alt="" width="100%">
            </div>
            <div class="col-md-6">
                <p>{{x.blog_contant|truncatewords:15}}</p>
                <button class="btn btn-info btn-lg"><a href="{% url 'Blog:detail_blog' x.slug %}">read</a></button>
                <button class="btn btn-danger btn-lg"><a href="{% url 'Blog:edit_blog' x.pk %}">Edit</a></button>
            </div>
        </div>
    {% if not forloop.last %}
    <hr>
    {% endif %}

    {% endfor %}

 </div>
{% endblock %}