My_Block_Project/App_Blog/urls.py
from django.urls import path
from . import views
app_name='Blog'

urlpatterns=[
    path('',views.Blog_list_page.as_view(),name='blog_list'),
    path('create/',views.CreatBlock.as_view(),name='create_block'),
    path('detail/<str:slug>/',views.Detailblockfunc,name='detail_blog'),
    path('liked/<int:pk>/',views.likefunction,name='liked'),
    path('dislike/<int:pk>/',views.dislikefunc,name='dislike'),
    path('my-blog/',views.MyBlog_list.as_view(),name='my_blog'),
    path('edit-blog/<pk>/',views.UpdateBlog.as_view(),name='edit_blog'),
    path('delete-comment/<pk>/',views.DeleteMycomment,name='delete_comment'),
]

My_Block_Project/Login_app/urls.py
from django.urls import path
from . import views

app_name='Login_app'
urlpatterns=[
    path('singup/',views.sign_up,name='signup'),
    path('login/',views.mylogin,name='login'),
    path('logout/',views.logout_func,name='logout'),
    path('profile/',views.profile,name='profile'),
    path('change_profile/',views.userchange,name='changeProfile'),
    path('password/',views.change_passwordform,name='change_pass'),
    path('add_pro_pic/',views.update_pro_pic,name='add_pic'),
    path('change_pro_pic/',views.change_pro_pic,name='change_pic')
]

My_Block_Project/My_Block_Project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns,static
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),

    path('account/',include('Login_app.urls')),

    path('blog/',include('App_Blog.urls')),
    path('',views.index,name='index')

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

My_Block_Project/Login_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfile(models.Model):
    user=models.OneToOneField(User,related_name='user_profile',on_delete=models.CASCADE)
    prifile_pic=models.ImageField(verbose_name='profile image ',upload_to='profile_pic')

My_Block_Project/Login_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth.models import User
from . import models

class UserSignupform(UserCreationForm):
    email=forms.EmailField(required=True)
    class Meta:
        model = User
        fields = ('username','email','password1','password2')

class ChangeUser(UserChangeForm):
    class Meta:
        model = User
        fields = ('username','email','first_name','last_name')


class InterprofilePic(forms.ModelForm):
    class Meta:
        model =models.UserProfile
        fields = ['prifile_pic']

My_Block_Project/Login_app/views.py
from django.shortcuts import render,HttpResponseRedirect,HttpResponse
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm,PasswordChangeForm,SetPasswordForm
from django.contrib.auth import logout,login,authenticate
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .forms import UserSignupform,ChangeUser,InterprofilePic

# Create your views here.

def sign_up(request):
    registration=False
    form=UserSignupform()
    if request.method=='POST':
        form=UserSignupform(request.POST)
        if form.is_valid():
            form.save()
            registration=True
    diction={
        'form':form,
        'registration':registration,
    }
    return render(request,'Login_app/signup.html',context=diction)



def mylogin(request):
    form=AuthenticationForm()
    diction={
        'form':form
    }
    if request.method=='POST':
        form=AuthenticationForm(request.POST)
        username=request.POST['username']
        password=request.POST['password']
        user=authenticate(username=username,password=password)

        if user is not None:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
        else:
                diction.update({'form':form})
                return HttpResponseRedirect(reverse('Login_app:login'))
    return render(request,'Login_app/login.html',context=diction)

@login_required(login_url='/')
def logout_func(request):
    logout(request)
    return HttpResponseRedirect(reverse('Login_app:login'))

@login_required(login_url='/')
def profile(request):
    return render(request,'Login_app/profile.html',context={})

@login_required(login_url='/')
def userchange(request):
    currant_user=request.user
    form=ChangeUser(instance=currant_user)
    if request.method == 'POST':
        form=ChangeUser(request.POST,instance=currant_user)
        if form.is_valid():
            form.save()
            # form=ChangeUser(instance=currant_user)
            return HttpResponseRedirect(reverse('Login_app:profile'))
    return render(request,'Login_app/change_profile.html',context={'form':form})

@login_required(login_url='/')
def change_passwordform(request):
    current_user=request.user
    form=PasswordChangeForm(current_user)
    if request.method== 'POST':
        form=PasswordChangeForm(current_user,data=request.POST)
        if form.is_valid():
            form.save()
    return render(request,'Login_app/change_password.html',context={'form':form})

@login_required(login_url='/')
def update_pro_pic(request):
    form = InterprofilePic()
    if request.method=='POST':
        form=InterprofilePic(request.POST,request.FILES)
        if form.is_valid():
            obj=form.save(commit=False)
            obj.user=request.user
            obj.save()
            return HttpResponseRedirect(reverse('Login_app:profile'))
    return render(request,'Login_app/pro_add_pic.html',context={'form':form})

@login_required(login_url='/')
def change_pro_pic(request):
    form=InterprofilePic(instance=request.user.user_profile)
    if request.method=='POST':
        form=InterprofilePic(request.POST,request.FILES,instance=request.user.user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('Login_app:profile'))

    return render(request, 'Login_app/pro_add_pic.html', context={'form': form})

My_Block_Project/templates/Login_app/change_password.html
{% extends 'base.html' %}
{% block title %}change password{% endblock%}
{% block body %}
{% load crispy_forms_tags %}
<div class="container">
    <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success btn-sm">change</button>
</form>
</div>
{% endblock%}

My_Block_Project/templates/Login_app/change_profile.html
{% extends 'base.html' %}
{% block title %}change profile{% endblock%}
{% block style %}
#div_id_password{
    display:none
}
#id_password{
display:none
}

{% endblock %}
{% block body %}
{% load crispy_forms_tags %}
<div class="container">
    <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success btn-sm">change</button>
</form>
    Change password <a href="{% url 'Login_app:change_pass' %}">hare</a>
</div>
{% endblock%}

My_Block_Project/templates/Login_app/login.html
{% extends 'base.html' %}

{% block title %}login page {% endblock %}

{% block body %}
{% load crispy_forms_tags %}
<div class="container">
    <h2>Login:</h2>
<form action="" method="post">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class="btn btn-success btn-sm">login</button>
</form>
</div>


{% endblock %}

My_Block_Project/templates/Login_app/pro_add_pic.html
{% extends 'base.html' %}
{% block title%}{% endblock %}

{% block body %}
{% load crispy_forms_tags %}
<div class="container">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-success btn-sm">add</button>
    </form>
</div>

{% endblock %}

My_Block_Project/templates/Login_app/profile.html
{% extends 'base.html' %}
{% block title %}Profile page {% endblock %}
{% block body %}
   <div class="container">
       <div class="row mt-2">
           <div class="col-md-3"></div>
           <div class="col-md-6">
               <h1>it is porfile page </h1>
{% if user.user_profile %}
<img src="/media/{{user.user_profile.prifile_pic}}" alt="" class="rounded-circle" width="100" height="100"><br>
               <a href="{% url 'Login_app:change_pic' %}" class="btn btn-info btn-md my-2">
                   change profile pic
               </a>
{% else %}
<img src="/media/profile_pic/as.jpg" alt="" height="200" width="200" class="rounded"><br>
               <a href="{% url 'Login_app:add_pic' %}" class="btn btn-info btn-md my-2">
                   add profile pic
               </a>
{% endif %}


    <p>Username : {{ user.username }}</p>
    <p>Email : {{ user.email}}</p>
    <p>name : {{ user.first_name }} {{user.last_name}}</p>


<a href="{% url 'Login_app:changeProfile' %}" class="btn btn-primary ">change info</a>
           </div>
           <div class="col-md-3"></div>
       </div>
   </div>
{% endblock %}

My_Block_Project/templates/Login_app/signup.html
{% extends 'base.html' %}
{% block title %}registration page {% endblock %}

{% block body %}

<div class="container">
    {% load crispy_forms_tags %}
{% if registration %}
<div class="alert alert-success">
    account create successfully <a href="{% url 'Login_app:login' %}">login hare </a>
</div>

{% else %}

<div class="row">
    <div class="col-md-6">
        <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success btn-block">add user</button>
</form>

<p>Already have an account <a href="{% url 'Login_app:login' %}"> sign up </a></p>
    </div>
</div>
{% endif %}
</div>

{% endblock %}